<?php

/**
 * @file
 * Page json output module.
 *
 * The main module file.
 */
 
/**
 * Implements hook_permission().
 */
function page_json_output_permission() {
  return array(
    'page_json_output_access' => array(
      'title' => 'Access page json output',
      'description' => 'Provide access for page json output.'
    ),
  );
}
 
/**
 * Implements hook_menu().
 */
function page_json_output_menu() {
  $items = array();
  $items['page_json/%/%node'] = array(
    'title' => t('Json Output'),
    'page callback' => 'page_json_output_view',
    'page arguments' => array(1, 2),
    'access arguments' => array('page_json_output_access'),
    'access callback' => 'page_json_output_access',
    'access arguments' => array(1, 2),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function page_json_output_access($siteapikey, $node) {
  $syskey = variable_get('siteapikey', 0);
  if (($syskey != 'No API Key yet' && $syskey != $siteapikey) || $node->type != 'page') {
    return FALSE;
  }
  return TRUE;
}
  
/**
 * Implements hook_form_alter().
 */
function page_json_output_form_alter(&$form, &$form_state, $form_id) {
  global $base_url;
  if ($form_id == 'system_site_information_settings') {
    $form['page_json_op'] = array(
      '#type' => 'fieldset',
      '#title' => t('Page Json Output'),
    );

    $apikey = variable_get('siteapikey');
    $form['page_json_op']['siteapikey'] = array(
      '#type' => 'textfield',
      '#title' => t('Site API Key'),
      '#default_value' => ($apikey != '') ? $apikey : 'No API Key yet',
      '#description' => t('for access json output of page type node the url format will be use <b>%url</b>', array('%url' => $base_url . '/page_json_op/[yourkey]/[nid]')), 
    );

    $form['actions']['submit']['#value'] = t('Update Configuration');
  }
}

/**
 * Menu callback for json output.
 */
function page_json_output_view($siteapikey, $node) {
  print drupal_json_output($node);
  drupal_exit();
}
